CREATE TABLE topicos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  mensaje VARCHAR(1000) NOT NULL,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(30) NOT NULL,
  autor VARCHAR(100) NOT NULL,
  curso VARCHAR(100) NOT NULL,
  CONSTRAINT uk_topico_titulo_mensaje UNIQUE (titulo, mensaje(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
